table fct_orders
	lineageTag: f31018b8-4787-434b-a6c5-b88efba170a6

	column order_id
		dataType: string
		lineageTag: 3755f95b-6676-4251-a3e5-dea08277862e
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: a50ee383-efe5-431a-82af-51ac44cff82a
		summarizeBy: none
		sourceColumn: customer_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: fcb408bd-5ac7-4bcc-a070-25e90e3bcc71
		summarizeBy: none
		sourceColumn: product_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column employee_id
		dataType: string
		lineageTag: beeb208e-e5f1-46e5-89d0-7a512b207c20
		summarizeBy: none
		sourceColumn: employee_id

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 93e10e3f-80ff-40d1-bbcc-e40717d36c1b
		summarizeBy: none
		sourceColumn: order_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column revenue
		dataType: double
		lineageTag: d0caf03e-7dd5-4105-be6d-2a9e29742d61
		summarizeBy: sum
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ship_via
		dataType: string
		lineageTag: aedc59e4-3897-4a81-a6fd-d477b00dd04c
		summarizeBy: none
		sourceColumn: ship_via

		annotation SummarizationSetBy = Automatic

	column ship_name
		dataType: string
		lineageTag: d05c3868-7f90-4eda-abb5-0af59eb620b3
		summarizeBy: none
		sourceColumn: ship_name

		annotation SummarizationSetBy = Automatic

	column ship_address
		dataType: string
		lineageTag: 992528cd-8fa3-4392-b60f-a3208e21ed53
		summarizeBy: none
		sourceColumn: ship_address

		annotation SummarizationSetBy = Automatic

	column ship_city
		dataType: string
		lineageTag: 42407186-8556-480b-a394-75e5f4d744e8
		summarizeBy: none
		sourceColumn: ship_city

		annotation SummarizationSetBy = Automatic

	column ship_region
		dataType: string
		lineageTag: a81878cf-36fb-41ce-9134-0652eaead137
		summarizeBy: none
		sourceColumn: ship_region

		annotation SummarizationSetBy = Automatic

	column ship_postal_code
		dataType: string
		lineageTag: 4333d8b9-ea31-4809-b36b-5831bbb513bc
		summarizeBy: none
		sourceColumn: ship_postal_code

		annotation SummarizationSetBy = Automatic

	column ship_country
		dataType: string
		lineageTag: d6aae72c-8b36-410a-aefc-4f9be5de9a27
		summarizeBy: none
		sourceColumn: ship_country

		annotation SummarizationSetBy = Automatic

	column freight
		dataType: double
		lineageTag: c236dca9-7c93-4ed6-a026-4efc2b2457f2
		summarizeBy: sum
		sourceColumn: freight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fct_orders = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Fonte = Value.NativeQuery(PostgreSQL.Database(#"Postgres Server", #"Northwind Database", [CreateNavigationProperties=false]), "SELECT order_id, product_id, customer_id, employee_id, order_date, revenue, ship_via, ship_name, ship_address, ship_city, ship_region, ship_postal_code, ship_country, freight#(lf)#(tab)FROM erp.orders", null, [EnableFolding=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"order_date", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

