table Recency
	lineageTag: 395400e7-c2e0-4306-a316-c6554ce7e821

	column Recency
		dataType: int64
		formatString: 0
		lineageTag: f856ab24-53e9-4f35-b0f4-92257319e725
		summarizeBy: sum
		sourceColumn: Recency

		annotation SummarizationSetBy = Automatic

	column Min
		dataType: int64
		formatString: 0
		lineageTag: 1198fb60-1bf2-4c09-af42-501b171ff5bb
		summarizeBy: sum
		sourceColumn: Min

		annotation SummarizationSetBy = Automatic

	column Max
		dataType: int64
		formatString: 0
		lineageTag: a73ef549-3cbd-4f76-b31c-4d0f31e8c6df
		summarizeBy: sum
		sourceColumn: Max

		annotation SummarizationSetBy = Automatic

	partition Recency = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlXSUTIAYmMDpVidaCUTENMQSJhB+MYgJohvaAQRMAKzwSIWEBEIG0RaIoBSbCwA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Recency = _t, Min = _t, Max = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Recency", Int64.Type}, {"Min", Int64.Type}, {"Max", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

